# Generated by Django 5.2.7 on 2025-11-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='input_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='job',
            name='output_file',
            field=models.FileField(blank=True, null=True, upload_to='cleaned_files/'),
        ),
    ]
